---
- name: Install RabbitMQ on Debian 12
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
        state: present
        update_cache: yes
      # Install essential packages including curl, gnupg, and apt-transport-https for fetching and handling package repositories.

    - name: Add Team RabbitMQ's main signing key
      shell: |
        curl -sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" | gpg --dearmor | tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null
      args:
        creates: /usr/share/keyrings/com.rabbitmq.team.gpg
      # Fetch and add the main signing key for Team RabbitMQ to verify their packages.

    - name: Add Cloudsmith Erlang repository key
      shell: |
        curl -sLf https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key | gpg --dearmor | tee /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg > /dev/null
      args:
        creates: /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg
      # Fetch and add the Cloudsmith repository key for Erlang packages used by RabbitMQ.

    - name: Add Cloudsmith RabbitMQ repository key
      shell: |
        curl -sLf https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key | gpg --dearmor | tee /usr/share/keyrings/rabbitmq.9F4587F226208342.gpg > /dev/null
      args:
        creates: /usr/share/keyrings/rabbitmq.9F4587F226208342.gpg
      # Fetch and add the Cloudsmith repository key for RabbitMQ server packages.

    - name: Add RabbitMQ APT repositories
      copy:
        dest: /etc/apt/sources.list.d/rabbitmq.list
        content: |
          ## Provides modern Erlang/OTP releases
          deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/debian bookworm main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/debian bookworm main

          # another mirror for redundancy
          deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/debian bookworm main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/debian bookworm main

          ## Provides RabbitMQ
          deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/debian bookworm main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/debian bookworm main

          # another mirror for redundancy
          deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-server/deb/debian bookworm main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-server/deb/debian bookworm main
      # Add the RabbitMQ APT repository configuration to the system's APT sources list.

    - name: Update APT cache
      apt:
        update_cache: yes
      # Update the APT cache to include the newly added repositories.

    - name: Install Erlang packages
      apt:
        name:
          - erlang-base
          - erlang-asn1
          - erlang-crypto
          - erlang-eldap
          - erlang-ftp
          - erlang-inets
          - erlang-mnesia
          - erlang-os-mon
          - erlang-parsetools
          - erlang-public-key
          - erlang-runtime-tools
          - erlang-snmp
          - erlang-ssl
          - erlang-syntax-tools
          - erlang-tftp
          - erlang-tools
          - erlang-xmerl
        state: present
      # Install necessary Erlang packages required for RabbitMQ.

    - name: Install RabbitMQ server
      apt:
        name: rabbitmq-server
        state: present
        install_recommends: yes
      # Install the RabbitMQ server package along with its recommended dependencies.

    - name: Get Erlang version
      shell: |
        erl -eval 'erlang:system_info(version).' -s init stop -s init stop
      register: erlang_version
      changed_when: false
      # Retrieve and register the current Erlang version installed on the system.

    - name: Print Erlang version
      debug:
        msg: "Erlang version: {{ erlang_version.stdout }}"
      # Output the Erlang version for verification purposes.

    - name: Get RabbitMQ version
      shell: |
        rabbitmqctl version
      register: rabbitmq_version
      changed_when: false
      # Retrieve and register the current RabbitMQ version installed on the system.

    - name: Print RabbitMQ version
      debug:
        msg: "RabbitMQ version: {{ rabbitmq_version.stdout }}"
      # Output the RabbitMQ version for verification purposes.
