---
- name: Install RabbitMQ on Debian 12
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - gnupg
          - curl
          - lsb-release
        state: present
        update_cache: yes

    - name: Add RabbitMQ signing key
      ansible.builtin.shell:
        cmd: |
          curl -sLf https://github.com/rabbitmq/signing-keys/releases/download/3.0/rabbitmq-release-signing-key.asc | gpg --dearmor > /usr/share/keyrings/com.rabbitmq.team.gpg
      args:
        creates: /usr/share/keyrings/com.rabbitmq.team.gpg

    - name: Add RabbitMQ APT repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/com.rabbitmq.team.gpg] https://dl.bintray.com/rabbitmq/debian {{ ansible_lsb.codename }} main"
        state: present

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install RabbitMQ
      apt:
        name: rabbitmq-server
        state: present

    - name: Start and enable RabbitMQ service
      systemd:
        name: rabbitmq-server
        state: started
        enabled: yes
