---
- name: Install Erlang and RabbitMQ on Debian
  hosts: debian_servers
  become: yes

  tasks:
    - name: Install dependencies
      apt:
        name:
          - software-properties-common
          - curl
          - gnupg2
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Erlang
      apt:
        name:
          - erlang
          - erlang-nox
        state: present

    - name: Check Erlang version
      command: "erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().' -noshell"
      register: erl_version

    - name: Display Erlang version
      debug:
        msg: "Erlang version: {{ erl_version.stdout }}"

    - name: Install RabbitMQ server
      apt:
        name: rabbitmq-server
        state: present

    - name: Start RabbitMQ server
      systemd:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Check RabbitMQ server status
      command: systemctl status rabbitmq-server
      register: rabbitmq_status

    - name: Display RabbitMQ server status
      debug:
        msg: "RabbitMQ status: {{ rabbitmq_status.stdout }}"
