---
- name: Remove RabbitMQ and Erlang from Debian 12
  hosts: debian_servers
  become: yes
  tasks:
    - name: Remove RabbitMQ server
      apt:
        name: rabbitmq-server
        state: absent
      # Remove the RabbitMQ server package

    - name: Remove Erlang packages
      apt:
        name:
          - erlang-base
          - erlang-asn1
          - erlang-crypto
          - erlang-eldap
          - erlang-ftp
          - erlang-inets
          - erlang-mnesia
          - erlang-os-mon
          - erlang-parsetools
          - erlang-public-key
          - erlang-runtime-tools
          - erlang-snmp
          - erlang-ssl
          - erlang-syntax-tools
          - erlang-tftp
          - erlang-tools
          - erlang-xmerl
        state: absent
      # Remove the Erlang packages

    - name: Remove RabbitMQ APT repository files
      file:
        path: "/etc/apt/sources.list.d/rabbitmq.list"
        state: absent
      # Remove the RabbitMQ APT sources list file

    - name: Remove RabbitMQ GPG keys
      file:
        path: "/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg"
        state: absent
      # Remove the Cloudsmith Erlang repository GPG key

    - name: Remove RabbitMQ GPG keys
      file:
        path: "/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg"
        state: absent
      # Remove the RabbitMQ server repository GPG key

    - name: Remove RabbitMQ GPG key
      file:
        path: "/usr/share/keyrings/com.rabbitmq.team.gpg"
        state: absent
      # Remove the Team RabbitMQ's main signing key

    - name: Clean up APT cache
      apt:
        autoclean: yes
        autoremove: yes
      # Clean up the APT package cache and remove unused packages
