- name: Remove Erlang and RabbitMQ on Debian
  hosts: debian_servers
  become: yes

  tasks:
    - name: Stop RabbitMQ server
      systemd:
        name: rabbitmq-server
        state: stopped
        enabled: no
      # Stops the RabbitMQ service and disables it from starting on boot

    - name: Uninstall RabbitMQ server
      apt:
        name: rabbitmq-server
        state: absent
      # Removes the RabbitMQ server package

    - name: Uninstall Erlang
      apt:
        name:
          - erlang
          - erlang-nox
        state: absent
      # Removes Erlang and associated packages

    - name: Remove RabbitMQ GPG keyring file
      file:
        path: /usr/share/keyrings/com.rabbitmq.team.gpg
        state: absent
      # Removes the RabbitMQ GPG keyring file

    - name: Remove dependencies
      apt:
        name:
          - software-properties-common
          - curl
          - gnupg2
          - apt-transport-https
        state: absent
      # Removes dependencies that were installed

    - name: Remove RabbitMQ repository
      apt_repository:
        repo: "deb https://dl.bintray.com/rabbitmq/debian bionic main"
        state: absent
      # Removes the RabbitMQ repository

    - name: Remove Erlang repository
      apt_repository:
        repo: "deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang"
        state: absent
      # Removes the Erlang repository

    - name: Remove RabbitMQ repository signing key
      apt_key:
        url: https://packages.rabbitmq.com/rabbitmq-release-signing-key.asc
        state: absent
      # Removes the RabbitMQ repository signing key

    - name: Update apt cache after removal
      apt:
        update_cache: yes
      # Updates the package list to reflect the removals
