- name: Remove Erlang and RabbitMQ from Debian
  hosts: debian_servers
  become: yes

  tasks:
    - name: Stop RabbitMQ server
      systemd:
        name: rabbitmq-server
        state: stopped
        enabled: no
      # Stop and disable the RabbitMQ service

    - name: Remove RabbitMQ server package
      apt:
        name: rabbitmq-server
        state: absent
      # Remove RabbitMQ server package

    - name: Remove Erlang packages
      apt:
        name:
          - erlang
          - erlang-nox
        state: absent
      # Remove Erlang and its minimal graphical components

    - name: Remove RabbitMQ APT repository
      block:
        - name: Remove RabbitMQ APT repository file
          file:
            path: /etc/apt/sources.list.d/rabbitmq.list
            state: absent
          # Remove the RabbitMQ APT repository file

        - name: Remove RabbitMQ GPG key
          file:
            path: /usr/share/keyrings/com.rabbitmq.team.gpg
            state: absent
          # Remove the RabbitMQ GPG key file

    - name: Update apt cache
      apt:
        update_cache: yes
      # Update the APT package cache to reflect the removal

    - name: Clean up any unused packages
      apt:
        autoclean: yes
        autoremove: yes
      # Remove unnecessary packages and clean up
