---
- name: Install RabbitMQ Server on Debian
  hosts: debian_servers
  become: yes
  tasks:
    - name: Update package index
      apt:
        update_cache: yes

    - name: Download RabbitMQ server .deb package
      get_url:
        url: "https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.13.6/rabbitmq-server_3.13.6-1_all.deb"
        dest: "/tmp/rabbitmq-server_3.13.6-1_all.deb"

    - name: Install RabbitMQ server
      apt:
        deb: "/tmp/rabbitmq-server_3.13.6-1_all.deb"

    - name: Resolve dependencies
      apt:
        name: "{{ ansible_facts.packages | selectattr('name', 'search', '^rabbitmq-server$') | map(attribute='name') | first }}"
        state: present

    - name: Clean up RabbitMQ server .deb package
      file:
        path: "/tmp/rabbitmq-server_3.13.6-1_all.deb"
        state: absent

    - name: Check RabbitMQ server status
      command: rabbitmqctl status
      register: rabbitmq_status
      ignore_errors: yes

    - name: Print RabbitMQ server status
      debug:
        msg: "{{ rabbitmq_status.stdout }}"
