---
- name: Install RabbitMQ on Debian 12
  hosts: all
  become: yes

  tasks:
    - name: Update apt repository cache
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
        state: present

    - name: Add RabbitMQ's main signing key
      shell: |
        curl -fsSL "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" | gpg --dearmor | tee /usr/share/keyrings/rabbitmq-team-archive-keyring.gpg > /dev/null

    - name: Add Erlang repository signing key
      shell: |
        curl -fsSL https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key | gpg --dearmor | tee /usr/share/keyrings/rabbitmq-erlang-archive-keyring.gpg > /dev/null

    - name: Add RabbitMQ repository signing key
      shell: |
        curl -fsSL https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key | gpg --dearmor | tee /usr/share/keyrings/rabbitmq-server-archive-keyring.gpg > /dev/null

    - name: Ensure the RabbitMQ repository file exists
      copy:
        content: |
          deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq-erlang-archive-keyring.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/debian bookworm main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq-erlang-archive-keyring.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/debian bookworm main
          deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq-server-archive-keyring.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/debian bookworm main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq-server-archive-keyring.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/debian bookworm main
        dest: /etc/apt/sources.list.d/rabbitmq.list
        mode: '0644'

    - name: Update apt cache after adding repositories
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Erlang and RabbitMQ
      apt:
        name:
          - erlang-base
          - erlang-asn1
          - erlang-crypto
          - erlang-eldap
          - erlang-ftp
          - erlang-inets
          - erlang-mnesia
          - erlang-os-mon
          - erlang-parsetools
          - erlang-public-key
          - erlang-runtime-tools
          - erlang-snmp
          - erlang-ssl
          - erlang-syntax-tools
          - erlang-tftp
          - erlang-tools
          - erlang-xmerl
          - rabbitmq-server
        state: present
        update_cache: yes
