- name: Install Erlang and RabbitMQ on Debian
  hosts: debian_servers
  become: yes

  tasks:
    - name: Install dependencies
      apt:
        name:
          - software-properties-common
          - curl
          - gnupg2
          - apt-transport-https
        state: present
        update_cache: yes
      # Install necessary dependencies for adding new repositories and installing packages

    - name: Add RabbitMQ GPG key
      command: >
        curl -1sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" |
        sudo gpg --dearmor |
        sudo tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null
      # Adds the RabbitMQ GPG key for verifying packages

    - name: Add RabbitMQ APT repository
      block:
        - name: Add RabbitMQ Erlang repository
          command: >
            echo "deb [signed-by=/usr/share/keyrings/com.rabbitmq.team.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/debian bookworm main" |
            sudo tee /etc/apt/sources.list.d/rabbitmq.list
          # Add RabbitMQ Erlang repository

        - name: Add RabbitMQ server repository
          command: >
            echo "deb [signed-by=/usr/share/keyrings/com.rabbitmq.team.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/debian bookworm main" |
            sudo tee -a /etc/apt/sources.list.d/rabbitmq.list
          # Append RabbitMQ server repository to the sources list

    - name: Update apt cache
      apt:
        update_cache: yes
      # Update the APT package cache to ensure we get the latest package lists

    - name: Install Erlang
      apt:
        name:
          - erlang
          - erlang-nox
        state: present
      # Install Erlang and its minimal graphical components for RabbitMQ

    - name: Check Erlang version
      command: "erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().' -noshell"
      register: erl_version
      # Retrieve and register the version of Erlang installed

    - name: Display Erlang version
      debug:
        msg: "Erlang version: {{ erl_version.stdout }}"
      # Display the Erlang version for verification purposes

    - name: Install RabbitMQ server
      apt:
        name: rabbitmq-server
        state: present
      # Install RabbitMQ server

    - name: Start RabbitMQ server
      systemd:
        name: rabbitmq-server
        state: started
        enabled: yes
      # Ensure the RabbitMQ service is started and enabled to start on boot

    - name: Check RabbitMQ server status
      command: systemctl status rabbitmq-server
      register: rabbitmq_status
      # Check and register the status of the RabbitMQ server

    - name: Display RabbitMQ server status
      debug:
        msg: "RabbitMQ status: {{ rabbitmq_status.stdout }}"
      # Display the RabbitMQ server status for verification purposes

    - name: Get RabbitMQ version
      command: rabbitmqctl version
      register: rabbitmq_version_output
      changed_when: False
      # Retrieve and register the version of RabbitMQ installed

    - name: Display RabbitMQ version
      debug:
        msg: "RabbitMQ version: {{ rabbitmq_version_output.stdout }}"
      # Display the RabbitMQ version for verification purposes
