- name: Install RabbitMQ Server on Debian
  hosts: debian_servers
  become: yes
  tasks:
    - name: Ensure necessary packages are installed
      apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
        state: present

    - name: Copy the RabbitMQ installation script to the remote host
      copy:
        content: |
          #!/bin/sh

          # Install necessary packages
          sudo apt-get install curl gnupg apt-transport-https -y

          # Team RabbitMQ's main signing key
          curl -1sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null
          # Community mirror of Cloudsmith: modern Erlang repository
          curl -1sLf https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key | sudo gpg --dearmor | sudo tee /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg > /dev/null
          # Community mirror of Cloudsmith: RabbitMQ repository
          curl -1sLf https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key | sudo gpg --dearmor | sudo tee /usr/share/keyrings/rabbitmq.9F4587F226208342.gpg > /dev/null

          # Add apt repositories maintained by Team RabbitMQ
          sudo tee /etc/apt/sources.list.d/rabbitmq.list <<EOF
          # Provides modern Erlang/OTP releases
          deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/debian bookworm main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/debian bookworm main

          # another mirror for redundancy
          deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/debian bookworm main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/debian bookworm main

          # Provides RabbitMQ
          deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/debian bookworm main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/debian bookworm main

          # another mirror for redundancy
          deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-server/deb/debian bookworm main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-server/deb/debian bookworm main
          EOF

          # Update package indices
          sudo apt-get update -y

          # Install Erlang packages
          sudo apt-get install -y erlang-base \
                                  erlang-asn1 erlang-crypto erlang-eldap erlang-ftp erlang-inets \
                                  erlang-mnesia erlang-os-mon erlang-parsetools erlang-public-key \
                                  erlang-runtime-tools erlang-snmp erlang-ssl \
                                  erlang-syntax-tools erlang-tftp erlang-tools erlang-xmerl

          # Install rabbitmq-server and its dependencies
          sudo apt-get install rabbitmq-server -y --fix-missing
        dest: /tmp/install_rabbitmq.sh
        mode: '0755'

    - name: Run the RabbitMQ installation script
      command: /tmp/install_rabbitmq.sh
      args:
        chdir: /tmp

    - name: Ensure RabbitMQ server is started and enabled
      service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Check RabbitMQ server status
      command: rabbitmqctl status
      register: rabbitmq_status
      ignore_errors: yes

    - name: Print RabbitMQ server status
      debug:
        msg: "{{ rabbitmq_status.stdout | default('RabbitMQ status check failed.') }}"

    - name: Clean up RabbitMQ installation script
      file:
        path: /tmp/install_rabbitmq.sh
        state: absent
