---
- name: Install and Verify RabbitMQ
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Add RabbitMQ Team signing key
      get_url:
        url: "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA"
        dest: /tmp/rabbitmq-team-key.asc

    - name: Import RabbitMQ Team signing key
      command: "gpg --dearmor /tmp/rabbitmq-team-key.asc | tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null"
      args:
        creates: /usr/share/keyrings/com.rabbitmq.team.gpg

    - name: Add Cloudsmith Erlang repository key
      get_url:
        url: "https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key"
        dest: /tmp/rabbitmq-erlang-key.asc

    - name: Import Erlang repository key
      command: "gpg --dearmor /tmp/rabbitmq-erlang-key.asc | tee /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg > /dev/null"
      args:
        creates: /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg

    - name: Add RabbitMQ repository key
      get_url:
        url: "https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key"
        dest: /tmp/rabbitmq-server-key.asc

    - name: Import RabbitMQ repository key
      command: "gpg --dearmor /tmp/rabbitmq-server-key.asc | tee /usr/share/keyrings/rabbitmq.9F4587F226208342.gpg > /dev/null"
      args:
        creates: /usr/share/keyrings/rabbitmq.9F4587F226208342.gpg

    - name: Add RabbitMQ APT repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ buster main"
        state: present

    - name: Install RabbitMQ
      apt:
        name: rabbitmq-server
        state: present
        update_cache: yes

    - name: Ensure RabbitMQ service is started
      service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Get Erlang version
      command: erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().' -sname check_version
      register: erlang_version
      changed_when: false

    - name: Print Erlang version
      debug:
        msg: "Erlang version: {{ erlang_version.stdout }}"

    - name: Get RabbitMQ version
      command: rabbitmqctl status | grep -i version
      register: rabbitmq_version
      changed_when: false

    - name: Print RabbitMQ version
      debug:
        msg: "RabbitMQ version: {{ rabbitmq_version.stdout }}"
