- name: Install RabbitMQ Server on Debian
  hosts: debian_servers
  become: yes
  tasks:
    - name: Update package index
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
        state: present

    - name: Add RabbitMQ signing keys
      command: >
        curl -1sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" | gpg --dearmor | tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null

    - name: Add RabbitMQ repositories
      apt_repository:
        repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/com.rabbitmq.team.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/debian bookworm main'
        state: present

    - name: Update package list
      apt:
        update_cache: yes

    - name: Install RabbitMQ server
      apt:
        name: rabbitmq-server
        state: present

    - name: Start RabbitMQ server
      service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Check RabbitMQ server status
      command: rabbitmqctl status
      register: rabbitmq_status
      ignore_errors: yes

    - name: Print RabbitMQ server status
      debug:
        msg: "{{ rabbitmq_status.stdout | default('RabbitMQ status check failed.') }}"
