---
- name: Install RabbitMQ
  hosts: all
  become: yes
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - curl
        state: present

    - name: Install Erlang repository
      apt_repository:
        repo: "deb https://packages.erlang-solutions.com/ubuntu $(lsb_release -cs) contrib"
        state: present
        update_cache: yes

    - name: Import Erlang GPG key
      apt_key:
        url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
        state: present

    - name: Install Erlang
      apt:
        name: erlang
        state: present

    - name: Add RabbitMQ apt repository
      apt_repository:
        repo: "deb https://packagecloud.io/rabbitmq/rabbitmq-server/debian buster main"
        state: present
        update_cache: yes

    - name: Import RabbitMQ GPG key
      apt_key:
        url: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
        state: present

    - name: Install RabbitMQ Server
      apt:
        name: rabbitmq-server
        state: present
        update_cache: yes
