- name: Install RabbitMQ Server on Debian
  hosts: debian_servers
  become: yes
  tasks:
    - name: Update package index
      apt:
        update_cache: yes

    - name: Add Erlang Solutions repository
      apt_repository:
        repo: "deb https://packages.erlang-solutions.com/debian $(lsb_release -cs) contrib"
        state: present
        filename: "erlang"

    - name: Install Erlang
      apt:
        name: erlang
        state: present

    - name: Download RabbitMQ server .deb package
      get_url:
        url: "https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.13.6/rabbitmq-server_3.13.6-1_all.deb"
        dest: "/tmp/rabbitmq-server_3.13.6-1_all.deb"

    - name: Install RabbitMQ server
      apt:
        deb: "/tmp/rabbitmq-server_3.13.6-1_all.deb"

    - name: Clean up RabbitMQ server .deb package
      file:
        path: "/tmp/rabbitmq-server_3.13.6-1_all.deb"
        state: absent

    - name: Ensure RabbitMQ server is started and enabled
      service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Check RabbitMQ server status
      command: rabbitmqctl status
      register: rabbitmq_status
      ignore_errors: yes

    - name: Print RabbitMQ server status
      debug:
        msg: "{{ rabbitmq_status.stdout | default('RabbitMQ status check failed.') }}"
