---
- name: Install Erlang and RabbitMQ dependencies
  hosts: all
  become: yes

  tasks:
    - name: Install dependencies
      apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Add Team RabbitMQ's main signing key
      command: >
        curl -1sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" |
        gpg --dearmor |
        tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null

    - name: Add Community mirror of Cloudsmith: modern Erlang repository key
      command: >
        curl -1sLf https://ppa1.novemberain.com/gpg.E495BB49CC4BBE5B.key |
        gpg --dearmor |
        tee /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg > /dev/null

    - name: Add Erlang Solutions repository GPG key
      command: >
        curl -fsSL https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc |
        gpg --dearmor |
        tee /usr/share/keyrings/erlang_solutions.gpg > /dev/null

    - name: Add RabbitMQ and Erlang Solutions repositories
      copy:
        content: |
          deb [signed-by=/usr/share/keyrings/erlang_solutions.gpg] https://packages.erlang-solutions.com/ubuntu focal contrib
          deb [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.novemberain.com/rabbitmq/rabbitmq-erlang/deb/ubuntu focal main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.novemberain.com/rabbitmq/rabbitmq-erlang/deb/ubuntu focal main
        dest: /etc/apt/sources.list.d/rabbitmq.list

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Erlang packages
      apt:
        name:
          - erlang-base
          - erlang-asn1
          - erlang-crypto
          - erlang-eldap
          - erlang-ftp
          - erlang-inets
          - erlang-mnesia
          - erlang-os-mon
          - erlang-parsetools
          - erlang-public-key
          - erlang-runtime-tools
          - erlang-snmp
          - erlang-ssl
          - erlang-syntax-tools
          - erlang-tftp
          - erlang-tools
          - erlang-xmerl
        state: present
