---
- name: Install RabbitMQ
  hosts: all
  become: yes
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - curl
        state: present

    - name: Install Erlang repository (using 'focal' as a compatible release)
      apt_repository:
        repo: "deb https://packages.erlang-solutions.com/ubuntu focal contrib"
        state: present
        update_cache: yes

    - name: Import Erlang GPG key
      command: curl -fsSL https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc | gpg --dearmor -o /etc/apt/trusted.gpg.d/erlang.gpg

    - name: Install Erlang
      apt:
        name: erlang
        state: present

    - name: Add RabbitMQ apt repository
      apt_repository:
        repo: "deb https://packagecloud.io/rabbitmq/rabbitmq-server/debian buster main"
        state: present
        update_cache: yes

    - name: Import RabbitMQ GPG key
      command: curl -fsSL https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey | gpg --dearmor -o /etc/apt/trusted.gpg.d/rabbitmq.gpg

    - name: Install RabbitMQ Server
      apt:
        name: rabbitmq-server
        state: present
        update_cache: yes
