- name: Remove Erlang and RabbitMQ from Debian
  hosts: debian_servers
  become: yes

  tasks:
    - name: Stop RabbitMQ server
      systemd:
        name: rabbitmq-server
        state: stopped
      # Stops the RabbitMQ service

    - name: Disable RabbitMQ server from starting on boot
      systemd:
        name: rabbitmq-server
        enabled: no
      # Disables RabbitMQ from starting automatically on system boot

    - name: Uninstall RabbitMQ server
      apt:
        name: rabbitmq-server
        state: absent
      # Removes the RabbitMQ server package

    - name: Uninstall Erlang
      apt:
        name:
          - erlang
          - erlang-nox
        state: absent
      # Removes Erlang and associated packages

    - name: Remove RabbitMQ repository
      apt_repository:
        repo: "deb https://dl.bintray.com/rabbitmq/debian bionic main"
        state: absent
      # Removes the RabbitMQ repository

    - name: Remove Erlang repository
      apt_repository:
        repo: "deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang"
        state: absent
      # Removes the Erlang repository

    - name: Remove RabbitMQ repository signing key
      apt_key:
        url: https://packages.rabbitmq.com/rabbitmq-release-signing-key.asc
        state: absent
      # Removes the RabbitMQ repository signing key

    - name: Purge dependencies
      apt:
        name: "{{ item }}"
        state: absent
      with_items:
        - software-properties-common
        - curl
        - gnupg2
        - apt-transport-https
      # Purges dependencies that were installed

    - name: Update apt cache after removal
      apt:
        update_cache: yes
      # Updates the package list to reflect the removals
